dist: bionic
language: python

python:
  - '3.6'

addons:
  chrome: stable

branches:
  only:
    - pur_beurre_P10
    
install:
  - pip install pipenv
  - pipenv install --dev

before_script:
  # ajouter tchappui-webdrivers dans requirements.txt
  - install-webdrivers

env:
  global:
    - DJANGO_SETTINGS_MODULE="pur_beurre.settings.travis"

services:
  - postgresql

script:
  - python pur_beurre/manage.py test -v2
