language: python

python:
  - '3.6'

branches:
  only:
    - pur_beurre_P10
    
before_script:
  - pip install pipenv
  - pipenv install --dev

env:
  global:
    - DJANGO_SETTINGS_MODULE="pur_beurre.settings.travis"

services:
  - postgresql

script:
  - python manage.py test -v2
