# Generated by Django 3.0.5 on 2020-04-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('nutrition_grade_fr', models.CharField(max_length=1)),
                ('url', models.URLField(max_length=250)),
                ('image_url', models.URLField(max_length=250)),
                ('category', models.ManyToManyField(to='food.Category')),
            ],
        ),
    ]
